### ISSUE TITLE
Add GitLab emulation

### ISSUE THREAD

**Issue by fabjan** [fabjan/poopline#5]
Look for .gilab-ci.yml.

If both GitLab and GitHub pipelines are detected, halt and let user select file via flags.

This example file should work like https://github.com/fabjan/poopline/blob/80b31ad/test/test_workflow.yml

```
stages:
  - test

echo_works:
  stage: test
  script:
    - echo foo

redirection_and_diff:
  stage: test
  script:
    - echo foo > bar.txt
    - echo baz >> bar.txt
    - diff <(echo -e "foo\nbaz") bar.txt
```

YAML nodes that must be implemented:
- stages
- jobs.stage
- jobs.before_script
- jobs.script
- jobs.after_script

If adding environment in this issue:
- jobs.environment

We probably need the `default` global version for each of the implemented nodes as well.

Reference: https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html

## Comparisons to the GitHub emulation

As far as I can tell, GitLab has one pipeline per repository, the yaml file.
GitHub can have multiple pipelines.

GitLab jobs run in stages, all jobs in one stage must complete successfully before the next step can start.
GitHub just runs all jobs that can run as soon as their "needs" are met.

GitHub job run steps are more structured, they have names etc.
In GitLab, a job has a list of steps.

We must support the step concept, most pipelines assume them and dependencies matter.

## Out of scope for this issue

https://docs.gitlab.com/ee/ci/yaml/#extends
I haven't tested YAML anchors, so no idea how well they work as an alternative.

https://docs.gitlab.com/ee/ci/yaml/#inherit

https://docs.gitlab.com/ee/ci/yaml/#rules

https://docs.gitlab.com/ee/ci/yaml/#workflow
